                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                    <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal" id="contact_form" method="post">
                    <div class="form-group">
                      <label for="name" class="col-md-3 control-label">Nome:</label>  
                      <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                      <input required type="text" name="name" class="form-control" id="name" placeholder="hxtutors" value="<?php echo $this->request->post('name') ?>">
                        </div>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="email" class="col-md-3 control-label">E-mail:</label>  
                      <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                      <input required type="email" name="email" class="form-control" id="email" placeholder="seuemail@site.com.br" value="<?php echo $this->request->post('email') ?>">
                        </div>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="username" class="col-md-3 control-label">Usuário:</label>  
                      <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                      <input required type="text" name="username" class="form-control" id="username" placeholder="hxtutors" value="<?php echo $this->request->post('username') ?>">
                        </div>
                      </div>
                    </div>  
                    <div class="form-group">
                      <label for="password" class="col-md-3 control-label">Senha:</label>  
                      <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                      <input required type="password" name="password" class="form-control" id="password" placeholder="Sua senha">
                        </div>
                      </div>
                    </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                          <button type="submit" class="btn btn-success">Cadastrar<span class="glyphicon glyphicon-send"></button>
                        </div>
                      </div>
                    </form>
                </div>
