                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                    <form action="<?php echo BASE; ?>login/logar/" class="form-horizontal" method="post">
                     <div class="form-group">
                      <label for="username" class="col-md-3 control-label">Usuário:</label>  
                      <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                      <input required type="text" name="username" class="form-control" id="username" placeholder="hxtutors" value="<?php echo $this->request->post('username') ?>">
                        </div>
                      </div>
                    </div> 
                      <div class="form-group">
                      <label for="password" class="col-md-3 control-label">Senha:</label>  
                      <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                      <input required type="password" name="password" class="form-control" id="password" placeholder="Sua senha">
                        </div>
                      </div>
                    </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                          <button type="submit" class="btn btn-success">Entrar<span class="glyphicon glyphicon-send"></button>
                        </div>
                      </div>
                    </form>
                </div>
