<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Fabiano S. Rocha">
	<meta name="generator" content="ADMC Framework">
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="description" content="A Igreja Assembleia de Deus Castiçal é uma comunidade comprometida em amar a Deus, amar uns aos outros e proclamar Jesus, vivenciando relacionamentos em Pequenos Grupos, de casa em casa, como também nos grandes ajuntamentos de Celebração.">
	<meta name="keywords" content="admc, igreja assembleia de Deus Castical, Vitoria da Conquista, igreja assembleia de Deus Castical, Jesus, Cristo, Deus, Evangelho, Celebrando Restauração, cr, pequenos grupos, pequeno grupo, biblia">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
	<link rel="stylesheet" href="<?php echo CSS; ?>bootstrap.css" type="text/css">
	<link rel="stylesheet" href="<?php //echo CSS; ?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php //echo CSS; ?>main.css" type="text/css">
	<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>chopslider.css"  />
	<script type="text/javascript" src="<?php echo JS; ?>jquery.js"></script>
        <!-- jQuery -->
    <script type="text/javascript" src="<?php echo JS; ?>jquery.id.chopslider-2.2.0.free.min.js"></script>
    <script type="text/javascript" src="<?php echo JS; ?>jquery.id.cstransitions-1.2.min.js"></script>

    <script type="text/javascript" src="<?php echo JS; ?>script.js"></script>
    <script type="text/javascript" src="<?php echo JS; ?>jquery.backgroundpos.js"></script>
    <script type="text/javascript" src="<?php echo JS; ?>jwplayer.js"></script>
    <script type="text/javascript" src="<?php echo JS; ?>html5shiv.js"></script>

    <link href="<?php echo CSS; ?>style.css" rel="stylesheet" type="text/css">
	<?php 
		echo $add_css;
		echo $add_js;
	?>
</head>
<body class="home blog iadmc-topbar">
	<div class="container">